spring:
  application:
    name: eden-rateLimiter
server:
  port: 8081

rate:
  count: 10
access:
  permits: 1
  timeout: 1


redisconfig:
  hosts: 127.0.0.1,127.0.0.2
  keyPrefix: rateLimiter
  defaultTTL: 60